### ISSUE TITLE
Win Installation failed: System command error

### ISSUE THREAD

**Issue by ThaiseRF** [swarm-lab/ROpenCVLite#6] opened 2018-01-23 18:04 UTC
Hi! Thanks for the reply.
So..I've followed the install instructions of CMake, Rtools (both in PATH) and devtools before the package.

I'm running R 3.4.3 on Windows64 10.
Rtools 3.3.0.1959
CMake 3.10.2

__
here is the line:

if(!require(pacman)) install.packages("pacman")
pacman::p_load(raster, rgdal, corrplot, RStoolbox, vegan, 
               psych, reshape2,EBImage, imager, OpenImageR, devtools,
               magick, dlib, Rcpp)

devtools::install_github("swarm-lab/ROpenCVLite")

__
the error:
[ 39%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfStandardAttributes.cpp.obj
gcc: error: Freitas/AppData/Local/Temp/RtmpkFyQub/devtools267c2b497a6a/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/build64: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpkFyQub/devtools267c2b497a6a/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/modules/core/include: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpkFyQub/devtools267c2b497a6a/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/modules/core/src: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpkFyQub/devtools267c2b497a6a/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/build64/modules/core: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpkFyQub/devtools267c2b497a6a/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/3rdparty/zlib: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpkFyQub/devtools267c2b497a6a/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/build64/3rdparty/zlib: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpkFyQub/devtools267c2b497a6a/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/3rdparty/include/opencl/1.2: No such file or directory
C:\Rtools\mingw_64\bin\windres.exe: preprocessing failed.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 39%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfStdIO.cpp.obj
[ 39%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfStringAttribute.cpp.obj
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfStringVectorAttribute.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTestFile.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfThreading.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTileDescriptionAttribute.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTileOffsets.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTiledMisc.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTiledInputFile.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTiledOutputFile.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTiledRgbaFile.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTimeCode.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTimeCodeAttribute.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfVecAttribute.cpp.obj
[ 41%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfVersion.cpp.obj
[ 41%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfWav.cpp.obj
[ 41%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfZipCompressor.cpp.obj
[ 41%] Linking CXX static library ../lib/libIlmImf.a
make[1]: *** Waiting for unfinished jobs....
[ 41%] Built target IlmImf
make: *** [all] Error 2
Warning: execução do comando 'sh ./configure.win' teve status 2
ERROR: configuration failed for package 'ROpenCVLite'
* removing 'C:/Users/Thaise Freitas/Documents/R/win-library/3.4/ROpenCVLite'
In R CMD INSTALL
Installation failed: run(bin, args = real_cmdargs, 
stdout_line_callback = real_callback(stdout),      
stderr_line_callback = real_callback(stderr), stdout_callback = real_block_callback,      
stderr_callback = real_block_callback, echo_cmd = echo, echo = show,      
spinner = spinner, error_on_status = fail_on_status, timeout = timeout) : System command error

**Comment by sjmgarnier** [comment] 2018-01-23 18:12
@ThaiseRF It looks like you're using an old version of RTools (3.3). Would you mind trying first with the latest version (3.4)? It can be downloaded from https://cran.r-project.org/bin/windows/Rtools/Rtools34.exe

**Comment by ThaiseRF** [comment] 2018-01-23 18:17
I've tried with Rtools 3.4 version before 3.3, then with 3.3 (frozen one) and both have the same error

**Comment by sjmgarnier** [comment] 2018-01-23 18:20
@ThaiseRF This is weird. Can you please post the entire installation log? Thanks.

**Comment by ThaiseRF** [comment] 2018-01-23 19:31
it's big! I've attached it, is it ok?
[sink.txt](https://github.com/swarm-lab/ROpenCVLite/files/1657317/sink.txt)

**Comment by sjmgarnier** [comment] 2018-01-23 19:44
@ThaiseRF It looks like the problem is with gcc/mingw not handling well spaces in the path (there is a space between "Thaise" and "Freitas" in your username, which translates in a space in the path to the installation folder). I'm not sure I can do anything about this. The obvious workaround would be to change your username so that it doesn't have a space in it, but I don't know if this would break anything else on Windows (I'm not too familiar with this OS).

**Comment by sjmgarnier** [comment] 2018-01-23 19:48
Since it's not a problem related to ROpenCVLite directly, I will close this issue. Feel free to keep commenting here if you find a solution to this problem.

**Comment by ThaiseRF** [comment] 2018-01-23 19:49
Hmm
I will try to change it (or create a new one) and let you know.
You already helped me a lot...
Thank you!!

**Closed by sjmgarnier** 2018-01-23 19:48 UTC

**Comment by sjmgarnier** [comment] 2018-01-23 19:51
@ThaiseRF No problem. Sorry I cannot be more helpful in resolving your problem.

**Comment by ThaiseRF** [comment] 2018-01-24 11:41
Hey! I created a new user and all worked out!
Thanks for helping out!

**Comment by sjmgarnier** [comment] 2018-01-24 14:48
@ThaiseRF I'm glad to hear it. I wish there was a less drastic solution to this problem.

**Comment by andburch** [comment] 2018-11-29 00:14
I had the same problem, and I'll deal with it similarly. However, Windows can deal with spaces-riddled paths as long as they are surrounded in quotes. So if you can somehow tell this "gcc/mingw" that the address should be 
`"C:/Users/Andrew Burchill/AppData/Local/Temp/Rtmpiumz94/R.INSTALL5d8225f7ff8/ROpenCVLite/src/opencv-3.4.3/..."`
and not
`C:/Users/Andrew Burchill/AppData/Local/Temp/Rtmpiumz94/R.INSTALL5d8225f7ff8/ROpenCVLite/src/opencv-3.4.3/...`
then it should work?

I don't know if specifying the path within quotes is even possible for gcc or whether it would mess other things up though...
